language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - ".firebase"
  - ".cache/bazel-disk-cache"
script:
  - ./.travis.sh
deploy:
- provider: script
  skip_cleanup: true
  script: yarn run deploy:ci
  on:
    branch: dev
- provider: pages
  local_dir: master
  target_branch: master
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  committer_from_gh: true
  on:
    branch: dev
- provider: gcs
  access_key_id: "$GCS_ACCESS_KEY"
  secret_access_key: "$GCS_SECRET"
  bucket: js-samples
  skip_cleanup: true
  local_dir: master/public
  upload_dir: "$TRAVIS_COMMIT"
  cache_control: max-age=31536000
  edge:
    source: jpoehnelt/dpl
    branch: feat/gcs_parallel
  acl: public-read
  on:
    all_branches: true
- provider: gcs
  access_key_id: "$GCS_ACCESS_KEY"
  secret_access_key: "$GCS_SECRET"
  bucket: js-samples
  skip_cleanup: true
  edge:
    source: jpoehnelt/dpl
    branch: feat/gcs_parallel
  acl: public-read
  local_dir: master/public
  upload_dir: "$TRAVIS_TAG"
  cache_control: max-age=31536000
  on:
    tag: true
env:
  global:
  - secure: PrUOO7uKgrGAcE9TII9m3/+UmlDO852BRuB3FxvvqWlnKOLi3ah9TObeol4xsXBP3eQbEE2YXpGzqPnb5DP2kmyarpelijhkJRkOhVaJlMY0+rNRJeuPRxlDYyQyUgRVsfBXqHwBfjVCREGjlJF7K93OoHAPdULeBzC3cog529/TVLrFFQ23f2fSrjMyziwcW5IqFlZDstUdrGq61rNrut5KjNyOA0mBZkMryZazU1bVB7KqGSo7kCPKhdmr0DKOSm/BKB99dQYfZv8hIeF7mSE/EUkPQkuSy56DySjnQzVOFnkC0hUWF30+aD2uNaAxyZMqam7VDSfUcnQYbIVwzgaI5OKAD9P1mnywsmESfpTi36U7ZkDROxTLe/SF7ZYJ4O/Nvly6O+gBsjjqvoAakvd21ceTdYmY2m+gbixo38IsLND/E5Ab3uJgDE1lKRGBkdfJ7b6qi2Dh0b2+G72sBUREhd5ls3RfFCA5PBLUPQ8azf7VjxPCi3Zjv4iAqvWAMB89yvRYUfz0+UaoymQ5QK48hOxtQJi2qmTLGwk+/AW5IiGM60iH7Cdv6LF+P78Yf0ESMIswbLo6vVIv/0LBqQFk/nYAQizZm4yMRrLHciItpW3PHlhVK8badqpPBW29dWEvajd56z0Wio+N6od7/AV9Fv25PrMdEisFQxsWE7M=
  - secure: bLVFbGkPT2hHm4Guj7XEevtWeCvpqngf4JYewRgLtDPqCFC1PuOHPrn5Ytz60MZ4OAcT9n6IiJ1fTd4t8ioYb2mZeWLJR3kBZ3LJxuWGhtZ+axriPofQGO22/ITaXLQAnFi/PNI7VUmC+5jOVLQNnGoINGvvh1fa6uRaEm/GUvZ/t15yWvUy91FgaZjAFaZugiigcVNsYGTQLwKThk102zyPl93slkmxrQ9DFh/t0ae5vyDh+KaVU8NnVGONtwX8OOIaJ7GHlpgoKmf86DibzCKZzQhxVcN0cN9Tl3VOsvhtjcK6DwqiKFjteBbmBvcQ5/XjlTuLqa3QWrNAC9RuFdo7bWWOzGEV9SP7+xnh3T26/K7wiYCaiHN5e9dsqIow9D8goCoNP4SwowRR+C+jGdly5YEzQsjemg1QgDAaiHfPGESJmj0n4/4VQB70urROUQLEjmyIqKoYn9b/qjKeD+78RsZFF/FvCGeSseaHBG/2bPIEDin/xC/aTwDPVncSRK7rNqU2rFVlg2EMZ6htr5XQQ/yaqN6byQVhvDfFRly54BZr6F9fGu+O6q+VWGvME7eogWS4xqrtFRmqNZ06u3K176LWzNRv2aTND3sE9D1cQbg/ngeQ0vdhqY5+jUXrJkLUNEwgDnQlqnCQkYfKT4Zkvjw4RDQ091Y70tuap4k=
  - secure: HLDwjten3aDu6L/LS5pn354w13dHpx2YOtozaj92CeIuhkDE5YMr7ZpvESE2FZXppgWH/XZOXeaUnj2sNarGVzeuMbBEuNPCg9ri5ccZhrJOUCTYsowmbnS4FjabKGqBXA2wTsOyQbYHlzp2ve3J/Lw+YsL5GVKT9M6GMG3MmBpuk8wKhmbdFN1PRVSQshNKXxXdzjpPCWVjXKpo/wqSwZgXk7rd2kAa3lGNy1AkTdVTjEGXT0mYExb4EOXWwU4GU0KbuPdl6Dv4sYOhe2f4xS9jzhYoZd7rJuhsoMWaMleoYjBAzGd3wOyrCBUY9PF0YeXb2R+KfTJicmXDelWRJWI83cUhSLwUP4P34jpi82Sh9TMEcT3qJD/1OuLZyxI67y0QB6PFpLs4Ab5f/HfDdG1BBCb1n1C80Tlw3nCV65C/rJNeG9XZ2Q1z1evEEKe4Jjr66ucatm25RIkZBf+I9x+iYcRid5HcyOoh2VE084YVJWieI7k3BMmZwHZFtEWZytX70TVJeWJkZCp9K+wkbcIwWwvql4ut7wf4tpDSZe7PEGSQ3qeKWBuZkO0+IzoEVRB/4BzkiKykTrGplpRClx7/Zmu6ae1GtQan4uOMgiElwXZXtwkOuIrYMxUG2vMEiIhL5ovL685xLrxxvu+dmrN9rz7ZI6BkyNA4gFGsPPQ=
  - secure: ThTkDTDi1qYoD8ZPkWl+VjjMKATcemn1cC7MkpkV+75flb3XcK7+vpUzpWYB2/0Qpo2zEBH7g0PgmVUHLafpHLJMmja17hwxlVP8lPDFWcIvyka/O6/Vf+cCiQNGEEhgz4H5l8dr2hk45bmfCLGcdsOBnpa81L8zw9TNRqLX4FHomJB5AvESZVPgmX75VvbvEJ5htS+b7vc4lz4DOpFKCqnkBtsKaHNkEPr2wijFvLZx9FTk/fYrJh2b8mkKOhItAcva2YjRDV6jlazIxanjCZlJdWnEk0+OZBgyhOoZwrdDqjs8KyfFvxbcvHgxt9y3Sbdh++1/JUBd6nlvBuCs7YNyGyTH3QzVN8m7jIzviVwmXFvvuVEDTdAcucRkkP8Q+CruBoKFcKQmNFMbdbNbw6ZuQ/1r8d9iUerdaAW8rzv0xv3rfRZITowq5XWms9Ih361clBaGKDnW9kjCea1Xr+OY8UO24rBRRFnbLAyXNxocfxoWgOZc2NfybDUHaxbgNo/VMZkdOVYSjOteq84/gSzhpOsASx3Ekmo+v/X/SwpUZa38uKCvnwmd7QHQkPd+LVUp/6zywqvg3ZFRCogzq4Ku+gEwpJJBMe5a2XZh7VfsEbrHIbOqZxPwQR9TcOwPRTsqi1rnuMu/sbxmNdBfwA22q9xSDUY1LLcpjpDtDC8=
  - secure: X05EsCaouyINMV2KiBeU+2W4LG/1KQoeiS58OOauv93Kjr6OAid9bBjPqsiSstYcuY23QiXYr2oPJzqEP345zCCOSQ4cIUHnBN3buuxA/4J5l9stc43LVjFJ/9jHcAZTaN3Ske4tFV6GJJbyUfMITbPtjYtppNjsiOtHx4aHBySwA4Fx83Uuo0cPgl+Xk2mmcQZ0Xy8GEnBlZBz1vRDXb6BluL8+4EgpnAQc08b8zCT0/H0hbhej+Kbl6r/d3RMmI+d3mSNOFy3Za5c7+E7XngU+W2VT6o0wtz+TOZkE5O7QC1XG9xtJVXc9HGqkWMUQHFErlELr+CUpyL2/CpjPIoWSdt1Sv80h/waEFOZQTc2DFbWYcn93L5YtGBULgFngITjRWD2Z+KF+DH4Vi58MPoBwhqc8gX/+HpRBGErU43RQZWuTze4NfL72W3EXZz3xWgzxpDRq9I4SjT/H4wXmGbgP4BdWatSp7vz4Scf/OybQXDPFohRrKTBuN1bKGaNxWIBCp7lK65q5fCTe+OxvPJxMKB+riP+2ZNp8KXnT0EUFY28c/kzPw2owZiZvDDN58WBvbY1QP1lxWjjGAdiZt1Wtp4mDYvHdm6oWfmmGxdYMACox45Zr/1i1lpoQtNqCs5dZoahcitDrFTV6AnnIkSWy+6HsxIxv+P2MfXsn74w=
