language: node_js
node_js:
- stable
script:
- npm run bootstrap
- npm run ci
- npm run build
before_deploy:
- "./build/before_deploy_pages.sh"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  committer_from_gh: true
  on:
    branch: master
env:
  global:
  - secure: PrUOO7uKgrGAcE9TII9m3/+UmlDO852BRuB3FxvvqWlnKOLi3ah9TObeol4xsXBP3eQbEE2YXpGzqPnb5DP2kmyarpelijhkJRkOhVaJlMY0+rNRJeuPRxlDYyQyUgRVsfBXqHwBfjVCREGjlJF7K93OoHAPdULeBzC3cog529/TVLrFFQ23f2fSrjMyziwcW5IqFlZDstUdrGq61rNrut5KjNyOA0mBZkMryZazU1bVB7KqGSo7kCPKhdmr0DKOSm/BKB99dQYfZv8hIeF7mSE/EUkPQkuSy56DySjnQzVOFnkC0hUWF30+aD2uNaAxyZMqam7VDSfUcnQYbIVwzgaI5OKAD9P1mnywsmESfpTi36U7ZkDROxTLe/SF7ZYJ4O/Nvly6O+gBsjjqvoAakvd21ceTdYmY2m+gbixo38IsLND/E5Ab3uJgDE1lKRGBkdfJ7b6qi2Dh0b2+G72sBUREhd5ls3RfFCA5PBLUPQ8azf7VjxPCi3Zjv4iAqvWAMB89yvRYUfz0+UaoymQ5QK48hOxtQJi2qmTLGwk+/AW5IiGM60iH7Cdv6LF+P78Yf0ESMIswbLo6vVIv/0LBqQFk/nYAQizZm4yMRrLHciItpW3PHlhVK8badqpPBW29dWEvajd56z0Wio+N6od7/AV9Fv25PrMdEisFQxsWE7M=
  - secure: JvBX1Ic5N7krcwOC5B4y1L6JU10a2up/DXn5PoFSdSbkcM06fygzo95vCuFv862ZwX0cWp2pVd2dnSh38GAJ2vwScm5PcqLXATLU/5dfRaLLJf+KA4oxGWPnzGO1D9W1NfNVlsTcSwN0WM+bSibdsicqHL6jp+P47/cZ388RQ+icaP72wmwWAWUUWW09OmpupI37q2gkOll/RgOJL437BzD40s2CuwnqUfO02xXM9gxeZNpU3FI/O7LOyUAXYldM9aEoNRTvAeUS71cjm7KFE/zWfCITBQcIwFgFmAG5QE6l24zhLyj3tOJlpQ6ZZVm0ssFLbjKJHhyx6mfWxKOvns5gg3RzCOyjjqKdRhj+0CQbRdGtGRV2nI1BGJl1lDZVRjj1ciPINHsAWhSDH8UDGFkconbNZT4vWLUhQgbqmn4VtIaUA3GJgTowaUBGyxXBc1Ef1alJuBz2kudm2Nd+gprj5Rt+qXRHiuUo9yBnyz9ah+/sy+SlVL79OZM5sfPT8oh0yVUOUAag4VF71kDdcV+0grDMiyTnH/x+0qQ8YiXGma1rmAXltpk6Rg+dfP/qAlMfLhjq+5QUv8u7wIcnzoH0C0psF+X8KomrCHzH14Z85iypy2afEslAu5qJjuOcZPB+fWFRgCDUkWAoOUXafBtADbz7rg7CFskhxMmZy1o=
