# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: 'node:17-slim'
    args:
      - ci
    entrypoint: npm
  - name: 'node:17-slim'
    args:
      - run
      - build
    entrypoint: npm
  - name: 'google/cloud-sdk:slim'
    args:
      - gsutil
      - '-m'
      - cp
      - '-r'
      - '-Z'  # gzip
      - dist/
      - 'gs://$_BUCKET/$REPO_NAME/$_PATH'
  # remove following after https://github.com/google/playground-elements/pull/279
  - name: 'google/cloud-sdk:slim'
    args:
      - gsutil
      - '-m'
      - setmeta
      - '-h'
      - 'content-type:video/mp2t'
      - 'gs://$_BUCKET/$REPO_NAME/$_PATH/**/*.ts'
  - name: 'google/cloud-sdk:slim'
    args:
      - gsutil
      - cors 
      - set
      - 'cors.json'
      - 'gs://$_BUCKET'
